-- ============================================================
-- Claims Adjudication Engine — Migration 011
-- Sync audit_event_type enum with currently emitted pipeline events
-- ============================================================

ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'SERVICE_DATE_AUTO_CORRECTED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'CLAUSE_FILTERING_APPLIED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'POLICY_DEFAULT';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'REASONING_ERROR';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'POLICY_CITATIONS_FALLBACK';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'RULES_ENGINE_FAILED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'SETTLEMENT_CALCULATION_FAILED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'COMPLETENESS_VALIDATED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'PROVIDER_NAME_ENRICHED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'POLICY_LIBRARY_MATCH';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'MEMBER_UNVERIFIED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'PROVIDER_UNVERIFIED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'SECONDARY_VALIDATION_COMPLETED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'SECONDARY_VALIDATION_SKIPPED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'ANTHROPIC_VALIDATION_COMPLETED';
ALTER TYPE audit_event_type ADD VALUE IF NOT EXISTS 'ANTHROPIC_VALIDATION_SKIPPED';
